# Site settings
title:          Alex Le
description:    "Alex Le lives in Colorado and is a software engineer. He likes to run, read, and tinker with technology and side projects."
tagline:        "Software Engineer, Minimalist, Improving Runner"
url:            "https://alexanderle.com"

# Google Analytics (GA4)
google_analytics: G-S03KNPH8PC

# Author
author:
  name:         Alex Le
  url:          https://alexanderle.com
  email:        alex.csm@gmail.com
  github:       alexle
  twitter:      alextrle
  linkedin:     alexle
  instagram:    alextrle

# Build settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
include:
  - _pages

# Assets
sass:
  style:        compressed
  quiet_deps:   true

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Jekyll Feed Configuration
feed:
  excerpt_only: true

# Permalinks
permalink:      /:title
paginate:       7

# Excludes
exclude:        [Gemfile, Gemfile.lock, vendor, node_modules, scripts/issue-to-post.sh, tests]
